# $Id: Makefile.dev,v 1.1.1.1 2011-03-25 02:18:46 okamoto Exp $
MAKEFILE = Makefile.dev
SHELL = /bin/sh
#OBJDIRS = server glview
OBJDIRS = server
TARGETDIRS = $(OBJDIRS) model julius-sp
SRCDIRS = ./ ./commonlib ./readconf
X3DDIR = ./x3d/parser/cpp/X3DParser

all: compile-x3d
	@for i in $(TARGETDIRS); \
	do ( echo compiling $$i; cd $$i; $(MAKE); cd ..; ) done

init:
	$(MAKE) -f $(MAKEFILE) init-objdirs
	$(MAKE) -f $(MAKEFILE) init-model
	$(MAKE) -f $(MAKEFILE) init-julius-sp

init-objdirs:
	@echo init directory; \
	for i in $(OBJDIRS); \
	do \
		if [ ! -d $$i ]; then \
			echo create $$i ...; \
			mkdir $$i; \
			cd $$i; lndir ../simserver ./; \
			mkdir commonlib; cd commonlib; lndir ../../commonlib ./; cd ..; \
			ln -s ../x3d/parser/cpp/X3DParser ./; \
			cd ..; \
			./emptydep.sh $$i; \
		fi;\
	done 

init-commonlib:
	cd $(DIR); \
	if [ ! -d commonlib ]; then \
		mkdir commonlib; cd commonlib; \
		lndir ../../commonlib; \
		../../emptydep.sh ./ ; \
		cd ..; \
	fi; \
	cd ..;

init-model: 
	$(MAKE) -f $(MAKEFILE) init-commonlib "DIR=model"
	$(MAKE) -C model/include -f Makefile.link

init-julius-sp:
	$(MAKE) -f $(MAKEFILE) init-commonlib "DIR=julius-sp" 

compile-x3d:
	$(MAKE) -C $(X3DDIR)

clean:
	@echo clean directory; \
	for i in $(TARGETDIRS); \
	do \
		cd $$i; make clean; cd ..; \
	done
	$(MAKE) -C $(X3DDIR) clean

clean-all:
	$(MAKE) -C model -f Makefile.dev clean-all
	$(MAKE) -C commonlib clean
	rm -rf julius-sp/commonlib
	rm -rf $(OBJDIRS)
