# $Id: Makefile.dev,v 1.1.1.1 2011-03-25 02:18:46 okamoto Exp $
MAKEFILE=Makefile.dev

DEPFILE = Makefile.dep

RM = rm -f

CXX = g++

DEBUG = -g -Wall 
DEFINE = -DUSE_ODE -DdDOUBLE -D CONTROLLER -D_DEBUG
#DEFINE = -DUSE_ODE -DdDOUBLE -D CONTROLLER
INCLUDE = -I./commonlib
CFLAGS = -pipe
CXXFLAGS = $(CFLAGS) $(DEFINE) $(INCLUDE) $(DEBUG) 

LD = $(CXX)
LDFLAGS = -L./ -lac -L./commonlib -lsigverse-common -ldl -lode

.SUFFIXES: .cpp .o

.cpp .o :
	$(CXX) $(CXXFLAGS) -o $@ -c $<

AC_SRCS = Controller.cpp ControllerLib.cpp
AC_OBJS = $(AC_SRCS:.cpp=.o)

SRCS = $(AC_SRCS)

AC_LIB = libac.a

all:
	$(MAKE) lib;
	$(MAKE) runac;
	$(MAKE) sendmsg;
	$(MAKE) compile-samples

lib:
	@echo compiling commonlib...;
	@cd commonlib; $(MAKE) "CXXFLAGS=$(CXXFLAGS)" ; cd ..;
	@echo Done;

runac : $(AC_LIB) runmain.cpp always
	$(CXX) -rdynamic -o $@ $(CXXFLAGS) runmain.cpp $(LDFLAGS)

sendmsg : lib
	$(CXX) -o $@ $(CXXFLAGS) sendmsg.cpp $(LDFLAGS)

always:

compile-samples:
	@echo "compile samples"
	cd samples; $(MAKE) "DEBUG=$(DEBUG)" "DEFINE=$(DEFINE)"; cd ..;

$(AC_LIB) : $(AC_OBJS)
	ar -cr $@ $(AC_OBJS)

depend:
	@echo creating dependency...;
	gcc -MM $(DEFINE) $(INCLUDE) $(SRCS) > $(DEPFILE)
	@for i in commonlib samples; \
	do \
		cd $$i; $(MAKE) depend; cd ..; \
	done

clean:
	$(RM) *.o *.a *.so *~ runac
	@for i in commonlib samples; \
	do \
		if cd $$i; then \
			$(MAKE) clean; cd ..; \
		fi \
	done

clean-all:
	$(MAKE) -f $(MAKEFILE) clean;
	rm -rf commonlib;
	find include -type l | xargs $(RM)

include $(DEPFILE)
