//    Generated by siggenac.           Thu Dec 17 14:22:54 JST 2009
/*
 *   SIGVerser Agent Controller Template Generator
 *
 *   To compile to create shared library, type
 *
 *    % g++ -shared -o TestController.so -I /user/local/include -DUSE_ODE -DCONTROLLER -DdDOUBLE -fPIC TestController.cpp
 *
 *   Or copy and use /usr/local/share/sigverse/samples/Makefile.controller.
 *
 */

#include <sigverse/Controller.h>
#include <sigverse/ControllerEvent.h>
//#include <sigverse/Logger.h>
//#include <sigverse/SimObj.h>
//#include <sigverse/ViewImage.h>
//#include <sigverse/RawSound.h>
//#include <sigverse/Logger.h>
//#include <sigverse/Text.h>


class TestController : public Controller
{
public:
	void 	onInit(InitEvent &evt);
	double 	onAction(ActionEvent &evt);
	void 	onRecvText(RecvTextEvent &evt);
	void	onRecvSound(RecvSoundEvent &evt);
	void	onRecvMessage(RecvMessageEvent &evt);
};


void 	 TestController::onInit(InitEvent &evt)
{

}

double 	 TestController::onAction(ActionEvent &evt)
{

}

void 	 TestController::onRecvText(RecvTextEvent &evt)
{

}

void	 TestController::onRecvSound(RecvSoundEvent &evt)
{

}

void	 TestController::onRecvMessage(RecvMessageEvent &evt)
{

}

extern "C"  Controller * createController ()
{
	return new TestController;
}
