# $Id: Makefile.glview,v 1.1.1.1 2011-03-25 02:18:50 okamoto Exp $

#DEFINE = -D IRWAS_TEST_CLIENT -D dDOUBLE
DEFINE = -D IRWAS_TEST_CLIENT -D _DEBUG

#DEBUG_CFLAGS = -g -Wall
LIBRARIES = -lGL -lglut -lode

SRCS = $(VIEW_SRCS)

include Makefile.base
