#
#
set(SIGSERVER_MAJOR_VERSION 2) 
set(SIGSERVER_MINOR_VERSION 3)
set(SIGSERVER_PATCH_VERSION 1)
set(SIGSERVER_VERSION ${SIGSERVER_MAJOR_VERSION}.${SIGSERVER_MINOR_VERSION})
set(SIGSERVER_FULL_VERSION ${SIGSERVER_MAJOR_VERSION}.${SIGSERVER_MINOR_VERSION}.${SIGSERVER_PATCH_VERSION})

if(MSVC10)
  set(VCVER "vs2010")
  set(VCVER_S "VC10")
elseif(MSVC11)
  set(VCVER "vs2012")
  set(VCVER_S "VC11")
elseif(MSVC12)
  set(VCVER "vs2013")
  set(VCVER_S "VC12")
else()
  set(VCVER "")
  set(VCVER "")
endif()

add_definitions( -std=c++11 -D__cplusplus=201103L )

include("${CMAKE_SOURCE_DIR}/cmake/SIGVerse_find_libs.cmake")

include_directories("${CMAKE_SOURCE_DIR}/srcs" "${ODE_ROOT_DIR}/include")
#include_directories("/home/sigverse/gitrepo/sigverse/SIGServer/srcs" "${ODE_ROOT_DIR}/include")

if(WIN32)
#add_definitions(-DWIN32 -DIRWAS_SIMSERVER -DdDOUBLE -DSTRICT_INTERFACE -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS)
add_definitions(-DWIN32 -DdDOUBLE -DSTRICT_INTERFACE -DX3DPARSER_DISABLE_DEBUG_LOG -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS)
else()
#add_definitions(-DIRWAS_SIMSERVER -DdDOUBLE -DSTRICT_INTERFACE)
add_definitions(-DdDOUBLE -DSTRICT_INTERFACE -DX3DPARSER_DISABLE_DEBUG_LOG )
endif()


