#
#
set(SIGSERVER_MAJOR_VERSION 2) 
set(SIGSERVER_MINOR_VERSION 3)
set(SIGSERVER_PATCH_VERSION 1)
set(SIGSERVER_VERSION ${SIGSERVER_MAJOR_VERSION}.${SIGSERVER_MINOR_VERSION})
set(SIGSERVER_FULL_VERSION ${SIGSERVER_MAJOR_VERSION}.${SIGSERVER_MINOR_VERSION}.${SIGSERVER_PATCH_VERSION})

if(MSVC10)
  set(VCVER "vs2010")
  set(VCVER_S "VC10")
elseif(MSVC11)
  set(VCVER "vs2012")
  set(VCVER_S "VC11")
elseif(MSVC12)
  set(VCVER "vs2013")
  set(VCVER_S "VC12")
else()
  set(VCVER "")
  set(VCVER "")
endif()


include("${CMAKE_SOURCE_DIR}/cmake/SIGVerse_find_libs.cmake")

include_directories("${CMAKE_SOURCE_DIR}" "${ODE_ROOT_DIR}/include")

if(WIN32)
add_definitions(-DWIN32 -DUSE_ODE -DdDOUBLE -D CONTROLLER -D_CRT_SECURE_NO_WARNINGS )
else()
#add_definitions(-DIRWAS_SIMSERVER -DdDOUBLE -DSTRICT_INTERFACE)
add_definitions(-DdDOUBLE -DSTRICT_INTERFACE)
endif()


